In [1]:
import numpy as np

In [2]:
np.array([2,4,3,4])

array([2, 4, 3, 4])

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.zerow(3,3)

AttributeError: module 'numpy' has no attribute 'zerow'

In [5]:
np.zeros(3,3)

TypeError: Cannot interpret '3' as a data type

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((1,1))

array([[1.]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.linspace(2,10,20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [10]:
np.random.random(4)

array([0.84992462, 0.7414909 , 0.67021589, 0.37575433])

In [11]:
np.random.rand(5)

array([0.94199885, 0.40870655, 0.3575301 , 0.72518426, 0.88538514])

# Numpy 2021

In [12]:
a=np.array([1,2,3,4])

In [13]:
type(a)

numpy.ndarray

In [14]:
dtype(a)

NameError: name 'dtype' is not defined

In [15]:
a.dtype

dtype('int64')

In [16]:
a.shape()

TypeError: 'tuple' object is not callable

In [17]:
a.shape

(4,)

In [18]:
a.dtype

dtype('int64')

In [19]:
a.size

4

In [20]:
a

array([1, 2, 3, 4])

In [21]:
a.ndim

1

In [22]:
a.itemsize

8

In [23]:
l1=[[2,4,3,5],[4,5,3,2]]

In [24]:
l1


[[2, 4, 3, 5], [4, 5, 3, 2]]

In [25]:
type(l1)

list

In [26]:
l2=np.array(l1)

In [27]:
l2

array([[2, 4, 3, 5],
       [4, 5, 3, 2]])

In [28]:
l2.ndim

2

In [29]:
l2.shape

(2, 4)

In [30]:
l2.size

8

In [31]:
l2.itemsize

8

In [32]:
l2.dtype

dtype('int64')

In [33]:
l2.dtype.name

'int64'

In [34]:
l2.dtype

dtype('int64')

In [35]:
b=np.array(a,dtype=int32)

NameError: name 'int32' is not defined

In [36]:
b=np.array(a,dtype='int32')

In [37]:
b.dtype.name

'int32'

In [38]:
b

array([1, 2, 3, 4], dtype=int32)

In [39]:
a

array([1, 2, 3, 4])

In [40]:
l2

array([[2, 4, 3, 5],
       [4, 5, 3, 2]])

In [41]:
l2.dtype

dtype('int64')

In [42]:
l2=np.array(l1,dtype='float32')

In [43]:
l2

array([[2., 4., 3., 5.],
       [4., 5., 3., 2.]], dtype=float32)

In [44]:
l2=np.array(l1,dtype='int32')

In [45]:
l2

array([[2, 4, 3, 5],
       [4, 5, 3, 2]], dtype=int32)

In [46]:
l2=np.array(a,dtype='complex')

In [47]:
l2

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [48]:
l2.dtype.name

'complex128'

In [49]:
l2=np.array(a,dtype='complex64')

In [50]:
l2

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64)

In [51]:
zero=np.zeros((2,3))

In [52]:
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
zero.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [54]:
zero.dtype

dtype('float64')

In [56]:
zero.dtype.name='int32'

AttributeError: attribute 'name' of 'numpy.dtype' objects is not writable

In [57]:
zero.dtype='int32'

In [58]:
zero

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [59]:
zero.shape

(2, 6)

In [60]:
zero.ndim

2

In [61]:
zero.size

12

In [62]:
zero.itemsize

4

In [63]:
one=np.ones((4,3,dtype='int32'))

SyntaxError: invalid syntax (<ipython-input-63-ee3a7ed07b7f>, line 1)

In [64]:
one=np.ones(((4,3),dtype='int32'))

SyntaxError: invalid syntax (<ipython-input-64-7ed8d2f0b11d>, line 1)

In [65]:
one=np.ones(4,3,dtype='int32')

TypeError: ones() got multiple values for argument 'dtype'

In [66]:
one=np.ones((4,3),dtype='int64')

In [67]:
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [68]:
one.dtype.name

'int64'

In [69]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [71]:
np.linspace(12,20,10)

array([12.        , 12.88888889, 13.77777778, 14.66666667, 15.55555556,
       16.44444444, 17.33333333, 18.22222222, 19.11111111, 20.        ])

In [72]:
np.linspace(12,20,10).reshape(2,5)

array([[12.        , 12.88888889, 13.77777778, 14.66666667, 15.55555556],
       [16.44444444, 17.33333333, 18.22222222, 19.11111111, 20.        ]])

In [73]:
np.linspace(12,20,10).reshape(5,2)

array([[12.        , 12.88888889],
       [13.77777778, 14.66666667],
       [15.55555556, 16.44444444],
       [17.33333333, 18.22222222],
       [19.11111111, 20.        ]])

In [74]:
np.arange(3,30,3.5)

array([ 3. ,  6.5, 10. , 13.5, 17. , 20.5, 24. , 27.5])

In [75]:
np.arange(3,30,3.5).reshape(2,4)

array([[ 3. ,  6.5, 10. , 13.5],
       [17. , 20.5, 24. , 27.5]])

In [76]:
(np.arange(3,30,3.5).reshape(2,4)).size

8

In [77]:
(np.arange(3,30,3.5).reshape(2,4)).ndim

2

In [78]:
(np.arange(3,30,3.5).reshape(2,4)).shape

(2, 4)

In [79]:
np.random?

Type:        module
String form: <module 'numpy.random' from '/usr/lib/python3/dist-packages/numpy/random/__init__.py'>
File:        /usr/lib/python3/dist-packages/numpy/random/__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initialize a BitGenerator
-----------------------

In [80]:
np.rand

AttributeError: module 'numpy' has no attribute 'rand'

In [81]:
np.random.binomial(2,3)

ValueError: p < 0, p > 1 or p is NaN

In [82]:
np.random.binomial(0.3)

TypeError: binomial() takes at least 2 positional arguments (1 given)

In [83]:
np.random.binomial(0.3,0.4)

0

In [84]:
np.random.randn((4,3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [85]:
np.random.randn([4,3])

TypeError: 'list' object cannot be interpreted as an integer

In [86]:
np.random.randn(3)

array([-0.05018839, -0.58031728,  0.50427009])

In [87]:
np.random.ranint?

Object `np.random.ranint` not found.


In [88]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

In [89]:
np.random.randint(3,size=10)

array([0, 2, 1, 1, 0, 0, 2, 1, 1, 2])

In [90]:
np.random.randint(5,size=10)

array([3, 2, 3, 1, 1, 1, 2, 2, 0, 3])

In [91]:
np.random.randint(5,size=10)


array([4, 1, 1, 0, 3, 2, 1, 1, 0, 1])

In [92]:
np.random.randint(5,size=10)

array([2, 1, 3, 2, 2, 2, 4, 2, 0, 0])

In [93]:
np.random.randint(5,size=(3,3))

array([[0, 0, 1],
       [2, 0, 0],
       [2, 0, 3]])

In [94]:
np.random.random((3,3))

array([[0.05584057, 0.25579341, 0.4205322 ],
       [0.67523579, 0.20015438, 0.93265315],
       [0.68731347, 0.65645917, 0.51391451]])

In [95]:
np.random.random((3,3),dtype='int32')

TypeError: random() got an unexpected keyword argument 'dtype'

In [96]:
np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method


In [97]:
a

array([1, 2, 3, 4])

In [98]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [99]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [100]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [101]:
a

array([1, 2, 3, 4])

In [102]:
a+2

array([3, 4, 5, 6])

In [103]:
a

array([1, 2, 3, 4])

In [104]:
a/1.5

array([0.66666667, 1.33333333, 2.        , 2.66666667])

In [105]:
;1

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<ipython-input-105-40ada5a0622f>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  1("")


TypeError: 'int' object is not callable

In [106]:
l1

[[2, 4, 3, 5], [4, 5, 3, 2]]

In [107]:
type(l1)

list

In [108]:
l2

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64)

In [109]:
l2=np.array(l2,dtype='int32')

<ipython-input-109-be52af8fce74>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  l2=np.array(l2,dtype='int32')


In [110]:
l2

array([1, 2, 3, 4], dtype=int32)

In [111]:
a+l2

array([2, 4, 6, 8])

In [112]:
a*l2

array([ 1,  4,  9, 16])

In [113]:
np.random.randint(5,size=10)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [114]:
a=np.array([0,1,2],[3,4,5],[6,7,8])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [115]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [116]:
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
a.ndim

2

In [118]:
a.shape

(3, 3)

In [119]:
a.dtype

dtype('int64')

In [120]:
a.itemsize


8

In [121]:
a.size

9

In [122]:
b=np.ones((3,3))

In [123]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [124]:
np.dot(a,b)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [125]:
a.dot(b)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [126]:
c=a.dot(b)*2

In [127]:
c

array([[ 6.,  6.,  6.],
       [24., 24., 24.],
       [42., 42., 42.]])

In [128]:
 c+=2

In [129]:
c

array([[ 8.,  8.,  8.],
       [26., 26., 26.],
       [44., 44., 44.]])

In [130]:
c.itemsize

8

In [131]:
c.size

9

In [132]:
([1,2,3]).dot([4,5,3])

AttributeError: 'list' object has no attribute 'dot'

In [133]:
x=np.array([1,2,3])

In [134]:
y=np.array([5,3,5])

In [135]:
x.dot(y)

26

In [136]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
a.sum()

36

In [138]:
sum(a)

array([ 9, 12, 15])

In [139]:
sum(a,axis=1)

TypeError: 'axis' is an invalid keyword argument for sum()

In [140]:
np.sum(a,axis=1)

array([ 3, 12, 21])

In [141]:
a.min()

0

In [142]:
min(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [143]:
a.sum()

36

In [144]:
sum(a)

array([ 9, 12, 15])

In [145]:
np.min(a)

0

In [146]:
np.min(a,axis=1)

array([0, 3, 6])

In [147]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
np.min(a,axis=0)

array([0, 1, 2])

In [149]:
a.min()

0

In [150]:
np.min(a)

0

In [151]:
np.std(a)

2.581988897471611

In [152]:
np.desc(a)

AttributeError: module 'numpy' has no attribute 'desc'

In [153]:
np.describe(a)

AttributeError: module 'numpy' has no attribute 'describe'

In [154]:
np.mean(a)

4.0

In [155]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [156]:
np.mean(a,axis=1)

array([1., 4., 7.])

In [157]:
np.mean(a,axis=0)

array([3., 4., 5.])

In [158]:
std(a)

NameError: name 'std' is not defined

In [159]:
a.std()

2.581988897471611

In [160]:
np.std(a)

2.581988897471611

In [161]:
np.std(a,axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [162]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [163]:
b=a.ravel()

In [164]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [165]:
b+=2.3

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [166]:
b+=4

In [167]:
b

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [168]:
b[3]

7

In [169]:
b[-3]

10

In [170]:
b[:5]

array([4, 5, 6, 7, 8])

In [171]:
b[::2]

array([ 4,  6,  8, 10, 12])

In [172]:
b[-1:-3]

array([], dtype=int64)

In [173]:
b[-1]

12

In [174]:
b[:-4]

array([4, 5, 6, 7, 8])

In [175]:
a[0:-1:2]

array([[4, 5, 6]])

In [176]:
b

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [177]:
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [178]:
b[:0]

array([], dtype=int64)

In [179]:
b[-np.size:0:2]

TypeError: bad operand type for unary -: 'function'

In [180]:
b[-(np.size):0:2]

TypeError: bad operand type for unary -: 'function'

In [181]:
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [182]:
a[1,2]

9

In [183]:
b

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [184]:
b[[1,2,3]]

array([5, 6, 7])

In [185]:
b[1,2,3]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [186]:
b[[3,5,2]]

array([7, 9, 6])

In [187]:
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [188]:
a[[1,2],[2,1]]

array([ 9, 11])

In [189]:
b[:-1:2]

array([ 4,  6,  8, 10])

In [190]:
b

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [191]:
b[-1]

12

In [192]:
b[:-1]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [193]:
a[0,2]

6

In [194]:
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [195]:
a[:2,1:]

array([[5, 6],
       [8, 9]])

In [196]:
a[0]

array([4, 5, 6])

In [197]:
a[0,:]

array([4, 5, 6])

In [198]:
a[,0]

SyntaxError: invalid syntax (<ipython-input-198-241a3fa00b9e>, line 1)

In [199]:
a[:,0]

array([ 4,  7, 10])

In [200]:
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [201]:
a[0,:]

array([4, 5, 6])

In [202]:
a


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [203]:
a[1:,1:]

array([[ 8,  9],
       [11, 12]])

In [204]:
a[1:,:2]

array([[ 7,  8],
       [10, 11]])

In [206]:
for i in a:
    print(i)

[4 5 6]
[7 8 9]
[10 11 12]


In [207]:
for i in a.flat:
    print(i)

4
5
6
7
8
9
10
11
12


In [208]:
np.apply_along_axis?

Signature: np.apply_along_axis(func1d, axis, arr, *args, **kwargs)
Docstring:
Apply a function to 1-D slices along the given axis.

Execute `func1d(a, *args, **kwargs)` where `func1d` operates on 1-D arrays
and `a` is a 1-D slice of `arr` along `axis`.

This is equivalent to (but faster than) the following use of `ndindex` and
`s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::

    Ni, Nk = a.shape[:axis], a.shape[axis+1:]
    for ii in ndindex(Ni):
        for kk in ndindex(Nk):
            f = func1d(arr[ii + s_[:,] + kk])
            Nj = f.shape
            for jj in ndindex(Nj):
                out[ii + jj + kk] = f[jj]

Equivalently, eliminating the inner loop, this can be expressed as::

    Ni, Nk = a.shape[:axis], a.shape[axis+1:]
    for ii in ndindex(Ni):
        for kk in ndindex(Nk):
            out[ii + s_[...,] + kk] = func1d(arr[ii + s_[:,] + kk])

Parameters
----------
func1d : function (M,) -> (Nj...)
    This function should accept 1-D arrays

In [209]:
np.apply_along_axis(sorted,0,a)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [210]:
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [211]:
np.apply_along_axis(sorted,0,b)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [212]:
b

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [213]:
np.apply_along_axis(reversed,0,a)

array([<reversed object at 0x7f84bb241970>,
       <reversed object at 0x7f84bb241550>], dtype=object)

In [214]:
np.apply_along_axis(reversed,0,b)

array(<reversed object at 0x7f84bb241790>, dtype=object)

In [215]:
list(np.apply_along_axis(reversed,0,a))

In [216]:
np.apply_along_axis(np.diag,0,a)

array([[[ 4,  5,  6],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 7,  8,  9],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [10, 11, 12]]])

In [217]:
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [218]:
np.apply_along_axis(np.diag,1,a)

array([[[ 4,  0,  0],
        [ 0,  5,  0],
        [ 0,  0,  6]],

       [[ 7,  0,  0],
        [ 0,  8,  0],
        [ 0,  0,  9]],

       [[10,  0,  0],
        [ 0, 11,  0],
        [ 0,  0, 12]]])

In [222]:
def MyIncr(a):
    return a+1
np.apply_along_axis(MyIncr,0,b)
        

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [223]:
b

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [224]:
def MyScaler(arr):
    return 0.5*arr
np.apply_along_axis(MyScaler,0,a)

array([[2. , 2.5, 3. ],
       [3.5, 4. , 4.5],
       [5. , 5.5, 6. ]])

In [225]:
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [2]:
a=[[1,4,5,3],[5,3,5,7]]

In [3]:
type(a)

list

In [4]:
a=np.array(a,dtype='int32')

In [5]:
a

array([[1, 4, 5, 3],
       [5, 3, 5, 7]], dtype=int32)

In [6]:
a.ndim

2

In [7]:
a.size

8

In [8]:
a.itemsize

4

In [9]:
a.shape

(2, 4)

In [10]:
a>4

array([[False, False,  True, False],
       [ True, False,  True,  True]])

In [11]:
a[a>4]

array([5, 5, 5, 7], dtype=int32)

In [12]:
a

array([[1, 4, 5, 3],
       [5, 3, 5, 7]], dtype=int32)

In [13]:
a[a<4.5]

array([1, 4, 3, 3], dtype=int32)

In [14]:
a.T

array([[1, 5],
       [4, 3],
       [5, 5],
       [3, 7]], dtype=int32)

In [15]:
a

array([[1, 4, 5, 3],
       [5, 3, 5, 7]], dtype=int32)

In [16]:
a.transpose()

array([[1, 5],
       [4, 3],
       [5, 5],
       [3, 7]], dtype=int32)

In [17]:
a.dtype='float32'

In [18]:
a

array([[1.e-45, 6.e-45, 7.e-45, 4.e-45],
       [7.e-45, 4.e-45, 7.e-45, 1.e-44]], dtype=float32)

In [19]:
a.dtype='int64'

In [20]:
a

array([[17179869185, 12884901893],
       [12884901893, 30064771077]])

In [21]:
a.dtype='int32'

In [22]:
a

array([[1, 4, 5, 3],
       [5, 3, 5, 7]], dtype=int32)

In [23]:
a

array([[1, 4, 5, 3],
       [5, 3, 5, 7]], dtype=int32)

In [24]:
b=np.linspace(12,24,8,dtype='int32').reshape(2,4)

In [25]:
b

array([[12, 13, 15, 17],
       [18, 20, 22, 24]], dtype=int32)

In [26]:
np.vstack((a,b))

array([[ 1,  4,  5,  3],
       [ 5,  3,  5,  7],
       [12, 13, 15, 17],
       [18, 20, 22, 24]], dtype=int32)

In [27]:
np.vstack(b,a)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [28]:
np.vstack((b,a))

array([[12, 13, 15, 17],
       [18, 20, 22, 24],
       [ 1,  4,  5,  3],
       [ 5,  3,  5,  7]], dtype=int32)

In [29]:
[np.vstack((b,a))>12]

[array([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])]

In [30]:
(b,a)[np.vstack((b,a))>12]

TypeError: only integer scalar arrays can be converted to a scalar index

In [31]:
[b,a][np.vstack((b,a))>12]

TypeError: only integer scalar arrays can be converted to a scalar index

In [32]:
((b,a))[np.vstack((b,a))>12]

TypeError: only integer scalar arrays can be converted to a scalar index

In [33]:
a

array([[1, 4, 5, 3],
       [5, 3, 5, 7]], dtype=int32)

In [34]:
b

array([[12, 13, 15, 17],
       [18, 20, 22, 24]], dtype=int32)

In [35]:
np.hstack((a,b))

array([[ 1,  4,  5,  3, 12, 13, 15, 17],
       [ 5,  3,  5,  7, 18, 20, 22, 24]], dtype=int32)

In [36]:
np.hstack((b,a))

array([[12, 13, 15, 17,  1,  4,  5,  3],
       [18, 20, 22, 24,  5,  3,  5,  7]], dtype=int32)

In [37]:
np.hstack?

Signature: np.hstack(tup)
Docstring:
Stack arrays in sequence horizontally (column wise).

This is equivalent to concatenation along the second axis, except for 1-D
arrays where it concatenates along the first axis. Rebuilds arrays divided
by `hsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the second axis,
    except 1-D arrays which can be any length.

Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays.

See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays along a new axis.
block : Assemble an nd-array from nested lists of blocks.
vstack : Sta

In [38]:
np.hstack((b,a))

array([[12, 13, 15, 17,  1,  4,  5,  3],
       [18, 20, 22, 24,  5,  3,  5,  7]], dtype=int32)

In [39]:
np.column_stack?

Signature: np.column_stack(tup)
Docstring:
Stack 1-D arrays as columns into a 2-D array.

Take a sequence of 1-D arrays and stack them as columns
to make a single 2-D array. 2-D arrays are stacked as-is,
just like with `hstack`.  1-D arrays are turned into 2-D columns
first.

Parameters
----------
tup : sequence of 1-D or 2-D arrays.
    Arrays to stack. All of them must have the same first dimension.

Returns
-------
stacked : 2-D array
    The array formed by stacking the given arrays.

See Also
--------
stack, hstack, vstack, concatenate

Examples
--------
>>> a = np.array((1,2,3))
>>> b = np.array((2,3,4))
>>> np.column_stack((a,b))
array([[1, 2],
       [2, 3],
       [3, 4]])
File:      /usr/lib/python3/dist-packages/numpy/lib/shape_base.py
Type:      function


In [40]:
np.stack?

Signature: np.stack(arrays, axis=0, out=None)
Docstring:
Join a sequence of arrays along a new axis.

The ``axis`` parameter specifies the index of the new axis in the
dimensions of the result. For example, if ``axis=0`` it will be the first
dimension and if ``axis=-1`` it will be the last dimension.

.. versionadded:: 1.10.0

Parameters
----------
arrays : sequence of array_like
    Each array must have the same shape.

axis : int, optional
    The axis in the result array along which the input arrays are stacked.

out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what stack would have returned if no
    out argument were specified.

Returns
-------
stacked : ndarray
    The stacked array has one more dimension than the input arrays.

See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
block : Assemble an nd-array from nested lists of blocks.
split : Split array into a list of mul

In [41]:
a,b,c=np.linspace(4,5,5),np.linspace(5,6,5),np.linspace(9,5,5)

In [42]:
a

array([4.  , 4.25, 4.5 , 4.75, 5.  ])

In [43]:
b

array([5.  , 5.25, 5.5 , 5.75, 6.  ])

In [44]:
c

array([9., 8., 7., 6., 5.])

In [45]:
np.column_stack(a,b,c)

TypeError: _column_stack_dispatcher() takes 1 positional argument but 3 were given

In [48]:
np.column_stack((a,b,c))

array([[4.  , 5.  , 9.  ],
       [4.25, 5.25, 8.  ],
       [4.5 , 5.5 , 7.  ],
       [4.75, 5.75, 6.  ],
       [5.  , 6.  , 5.  ]])

In [51]:
x=np.arange(20,40,2).reshape(2,5)

In [52]:
x

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [55]:
np.column_stack((a,x[0],x[1]))

array([[ 4.  , 20.  , 30.  ],
       [ 4.25, 22.  , 32.  ],
       [ 4.5 , 24.  , 34.  ],
       [ 4.75, 26.  , 36.  ],
       [ 5.  , 28.  , 38.  ]])

In [56]:
np.row_stack((a,b,c))

array([[4.  , 4.25, 4.5 , 4.75, 5.  ],
       [5.  , 5.25, 5.5 , 5.75, 6.  ],
       [9.  , 8.  , 7.  , 6.  , 5.  ]])

In [57]:
np.row_stack((b,x[0]))

array([[ 5.  ,  5.25,  5.5 ,  5.75,  6.  ],
       [20.  , 22.  , 24.  , 26.  , 28.  ]])

In [58]:
np.hsplit?

Signature: np.hsplit(ary, indices_or_sections)
Docstring:
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.],
       [  6.,   7.],
       [10.,  11.],
       [14.,  15.]])]
>>> np.hsplit(x, np.array([3, 6]))
[array([[ 0.,   1.,   2.],
       [ 4.,   5.,   6.],
       [ 8.,   9.,  10.],
       [12.,  13.,  14.]]),
 array([[ 3.],
       [ 7.],
       [11.],
       [15.]]),
 array([], shape=(4, 0), dtyp

In [59]:
np.vsplit?

Signature: np.vsplit(ary, indices_or_sections)
Docstring:
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
>>> np.vsplit(x, np.array([3, 6]))
[array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]]), array([], shape=(0, 4), dtype=float64)]

With a higher dimensional array the split is still along the first axis.

>>> x = n

In [60]:
x

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [61]:
np.split(x,2)

[array([[20, 22, 24, 26, 28]]), array([[30, 32, 34, 36, 38]])]

In [62]:
x=np.random(4,4)

TypeError: 'module' object is not callable

In [63]:
np.random.random(4,4)

TypeError: random() takes at most 1 positional argument (2 given)

In [64]:
np.random.random((4,4))

array([[0.73849814, 0.24282516, 0.72431116, 0.65872756],
       [0.70012883, 0.98079211, 0.555155  , 0.79570765],
       [0.57756884, 0.28300112, 0.45546473, 0.72364397],
       [0.74933651, 0.86328512, 0.12902573, 0.46850697]])

In [65]:
x=np.random.random((4,4))

In [66]:
x

array([[0.17175721, 0.18721689, 0.61897699, 0.18303924],
       [0.86302244, 0.0176555 , 0.0792593 , 0.59782668],
       [0.59055497, 0.98413897, 0.43921678, 0.8540811 ],
       [0.78040781, 0.11984797, 0.69707767, 0.13658921]])

In [67]:
np.split(x,2)

[array([[0.17175721, 0.18721689, 0.61897699, 0.18303924],
        [0.86302244, 0.0176555 , 0.0792593 , 0.59782668]]),
 array([[0.59055497, 0.98413897, 0.43921678, 0.8540811 ],
        [0.78040781, 0.11984797, 0.69707767, 0.13658921]])]

In [68]:
np.split(x,2,axis=1)

[array([[0.17175721, 0.18721689],
        [0.86302244, 0.0176555 ],
        [0.59055497, 0.98413897],
        [0.78040781, 0.11984797]]),
 array([[0.61897699, 0.18303924],
        [0.0792593 , 0.59782668],
        [0.43921678, 0.8540811 ],
        [0.69707767, 0.13658921]])]

In [69]:
np.split(x,[2,5],axis=1)

[array([[0.17175721, 0.18721689],
        [0.86302244, 0.0176555 ],
        [0.59055497, 0.98413897],
        [0.78040781, 0.11984797]]),
 array([[0.61897699, 0.18303924],
        [0.0792593 , 0.59782668],
        [0.43921678, 0.8540811 ],
        [0.69707767, 0.13658921]]),
 array([], shape=(4, 0), dtype=float64)]

In [70]:
np.split(x,[3,],axis=1)

[array([[0.17175721, 0.18721689, 0.61897699],
        [0.86302244, 0.0176555 , 0.0792593 ],
        [0.59055497, 0.98413897, 0.43921678],
        [0.78040781, 0.11984797, 0.69707767]]),
 array([[0.18303924],
        [0.59782668],
        [0.8540811 ],
        [0.13658921]])]

In [71]:
np.split(x,[1,],axis=0)

[array([[0.17175721, 0.18721689, 0.61897699, 0.18303924]]),
 array([[0.86302244, 0.0176555 , 0.0792593 , 0.59782668],
        [0.59055497, 0.98413897, 0.43921678, 0.8540811 ],
        [0.78040781, 0.11984797, 0.69707767, 0.13658921]])]

In [72]:
np.split(x,[1,])

[array([[0.17175721, 0.18721689, 0.61897699, 0.18303924]]),
 array([[0.86302244, 0.0176555 , 0.0792593 , 0.59782668],
        [0.59055497, 0.98413897, 0.43921678, 0.8540811 ],
        [0.78040781, 0.11984797, 0.69707767, 0.13658921]])]

In [73]:
a

array([4.  , 4.25, 4.5 , 4.75, 5.  ])

In [74]:
b=a

In [76]:
print(id(a));print(id(b))

140274147758208
140274147758208


In [77]:
a[0]=11


In [78]:
b

array([11.  ,  4.25,  4.5 ,  4.75,  5.  ])

In [79]:
a

array([11.  ,  4.25,  4.5 ,  4.75,  5.  ])

In [80]:
del b[0]

ValueError: cannot delete array elements

In [81]:
del?

Object `del` not found.


In [82]:
np.del?

Object `np.del` not found.


In [83]:
b[0]=111

In [84]:
b

array([111.  ,   4.25,   4.5 ,   4.75,   5.  ])

In [85]:
a

array([111.  ,   4.25,   4.5 ,   4.75,   5.  ])

In [86]:
c=b

In [87]:
c[0]=22

In [88]:
a

array([22.  ,  4.25,  4.5 ,  4.75,  5.  ])

In [89]:
c

array([22.  ,  4.25,  4.5 ,  4.75,  5.  ])

In [90]:
b

array([22.  ,  4.25,  4.5 ,  4.75,  5.  ])

In [91]:
id(c)

140274147758208

In [92]:
id(a)

140274147758208

In [93]:
structered_arr=np.array([(54,8.5,5+4.3j,'sanjay'),(45,56.5,8+3.5j,'swapnil'),(98,6.2,9.3+3.0j,'chaitanya')],dtype=('int32,float32,c8,a(10)'))

ValueError: format number 4 of "int32,float32,c8,a(10)" is not recognized

In [94]:
structered_arr=np.array([(54,8.5,5+4.3j,'sanjay'),(45,56.5,8+3.5j,'swapnil'),(98,6.2,9.3+3.0j,'chaitanya')],dtype=('i4,f4,c8,a(10)'))

ValueError: format number 4 of "i4,f4,c8,a(10)" is not recognized

In [95]:
structered_arr=np.array([(54,8.5,5+4.3j,'sanjay'),(45,56.5,8+3.5j,'swapnil'),(98,6.2,9.3+3.0j,'chaitanya')],dtype=('i4,f4,c8,a10'))

In [96]:
structered_arr

array([(54,  8.5, 5. +4.3j, b'sanjay'), (45, 56.5, 8. +3.5j, b'swapnil'),
       (98,  6.2, 9.3+3.j , b'chaitanya')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', '<c8'), ('f3', 'S10')])

In [97]:
structered_arr[0]

(54, 8.5, 5.+4.3j, b'sanjay')

In [98]:
structered_arr['f2']

array([5. +4.3j, 8. +3.5j, 9.3+3.j ], dtype=complex64)

In [99]:
structered_arr?

Type:            ndarray
String form:    
[(54,  8.5, 5. +4.3j, b'sanjay') (45, 56.5, 8. +3.5j, b'swapnil')
 (98,  6.2, 9.3+3.j , b'chaitanya')]
Length:          3
File:            /usr/lib/python3/dist-packages/numpy/__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for th

In [100]:
np.real?

Signature: np.real(val)
Docstring:
Return the real part of the complex argument.

Parameters
----------
val : array_like
    Input array.

Returns
-------
out : ndarray or scalar
    The real component of the complex argument. If `val` is real, the type
    of `val` is used for the output.  If `val` has complex elements, the
    returned type is float.

See Also
--------
real_if_close, imag, angle

Examples
--------
>>> a = np.array([1+2j, 3+4j, 5+6j])
>>> a.real
array([1.,  3.,  5.])
>>> a.real = 9
>>> a
array([9.+2.j,  9.+4.j,  9.+6.j])
>>> a.real = np.array([9, 8, 7])
>>> a
array([9.+2.j,  8.+4.j,  7.+6.j])
>>> np.real(1 + 1j)
1.0
File:      /usr/lib/python3/dist-packages/numpy/lib/type_check.py
Type:      function


In [101]:
np.imag?

Signature: np.imag(val)
Docstring:
Return the imaginary part of the complex argument.

Parameters
----------
val : array_like
    Input array.

Returns
-------
out : ndarray or scalar
    The imaginary component of the complex argument. If `val` is real,
    the type of `val` is used for the output.  If `val` has complex
    elements, the returned type is float.

See Also
--------
real, angle, real_if_close

Examples
--------
>>> a = np.array([1+2j, 3+4j, 5+6j])
>>> a.imag
array([2.,  4.,  6.])
>>> a.imag = np.array([8, 10, 12])
>>> a
array([1. +8.j,  3.+10.j,  5.+12.j])
>>> np.imag(1 + 1j)
1.0
File:      /usr/lib/python3/dist-packages/numpy/lib/type_check.py
Type:      function


In [105]:
real_imag=np.array([3+5.3j,8+3.5j,5+6.3j],dtype='complex64')

In [106]:
print('hello')

hello


In [107]:
real_imag

array([3.+5.3j, 8.+3.5j, 5.+6.3j], dtype=complex64)

In [108]:
real_imag.real

array([3., 8., 5.], dtype=float32)

In [109]:
real_imag.imag

array([5.3, 3.5, 6.3], dtype=float32)

In [110]:
np.save('structered_arr',structered_arr)

In [111]:
a=np.load('structered_arr.npy')

In [112]:
a

array([(54,  8.5, 5. +4.3j, b'sanjay'), (45, 56.5, 8. +3.5j, b'swapnil'),
       (98,  6.2, 9.3+3.j , b'chaitanya')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', '<c8'), ('f3', 'S10')])

In [113]:
a['f1']

array([ 8.5, 56.5,  6.2], dtype=float32)

In [114]:
a

array([(54,  8.5, 5. +4.3j, b'sanjay'), (45, 56.5, 8. +3.5j, b'swapnil'),
       (98,  6.2, 9.3+3.j , b'chaitanya')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', '<c8'), ('f3', 'S10')])

In [115]:
b

array([22.  ,  4.25,  4.5 ,  4.75,  5.  ])

In [116]:
x

array([[0.17175721, 0.18721689, 0.61897699, 0.18303924],
       [0.86302244, 0.0176555 , 0.0792593 , 0.59782668],
       [0.59055497, 0.98413897, 0.43921678, 0.8540811 ],
       [0.78040781, 0.11984797, 0.69707767, 0.13658921]])

In [117]:
np.savez?


Signature: np.savez(file, *args, **kwds)
Docstring:
Save several arrays into a single file in uncompressed ``.npz`` format.

If arguments are passed in with no keywords, the corresponding variable
names, in the ``.npz`` file, are 'arr_0', 'arr_1', etc. If keyword
arguments are given, the corresponding variable names, in the ``.npz``
file will match the keyword names.

Parameters
----------
file : str or file
    Either the filename (string) or an open file (file-like object)
    where the data will be saved. If file is a string or a Path, the
    ``.npz`` extension will be appended to the filename if it is not
    already there.
args : Arguments, optional
    Arrays to save to the file. Since it is not possible for Python to
    know the names of the arrays outside `savez`, the arrays will be saved
    with names "arr_0", "arr_1", and so on. These arguments can be any
    expression.
kwds : Keyword arguments, optional
    Arrays to save to the file. Arrays will be saved in the file wit

In [118]:
np.savez('mulit_uncmp',b,x)

In [119]:
np.savetxt('multi_txt',b,x)

ValueError: invalid fmt: array([[0.17175721, 0.18721689, 0.61897699, 0.18303924],
       [0.86302244, 0.0176555 , 0.0792593 , 0.59782668],
       [0.59055497, 0.98413897, 0.43921678, 0.8540811 ],
       [0.78040781, 0.11984797, 0.69707767, 0.13658921]])

In [120]:
np.savetxt?

Signature:
np.savetxt(
    fname,
    X,
    fmt='%.18e',
    delimiter=' ',
    newline='\n',
    header='',
    footer='',
    comments='# ',
    encoding=None,
)
Docstring:
Save an array to a text file.

Parameters
----------
fname : filename or file handle
    If the filename ends in ``.gz``, the file is automatically saved in
    compressed gzip format.  `loadtxt` understands gzipped files
    transparently.
X : 1D or 2D array_like
    Data to be saved to a text file.
fmt : str or sequence of strs, optional
    A single format (%10.5f), a sequence of formats, or a
    multi-format string, e.g. 'Iteration %d -- %10.5f', in which
    case `delimiter` is ignored. For complex `X`, the legal options
    for `fmt` are:

    * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
      like `' (%s+%sj)' % (fmt, fmt)`
    * a full string specifying every real and imaginary part, e.g.
      `' %.4e %+.4ej %.4e %+.4ej %.4e %+.4ej'` for 3 columns
    * a list of specifiers, one pe

In [121]:
np.savetxt('multi_txt',(b,x),header='plain-txt array')

/usr/lib/python3/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


TypeError: Mismatch between array dtype ('object') and format specifier ('%.18e')

In [122]:
np.savetxt('multi_txt',(b,x),header='plain-txt array',delimiter=',')

/usr/lib/python3/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


TypeError: Mismatch between array dtype ('object') and format specifier ('%.18e')

In [123]:
np.savetxt('multi_txt',b,header='plain-txt array')

In [124]:
np.savez_compressed('multi_cmp',b,x)

In [128]:
a=np.load?

Signature:
np.load(
    file,
    mmap_mode=None,
    allow_pickle=False,
    fix_imports=True,
    encoding='ASCII',
)
Docstring:
Load arrays or pickled objects from ``.npy``, ``.npz`` or pickled files.

.. warning:: Loading files that contain object arrays uses the ``pickle``
             module, which is not secure against erroneous or maliciously
             constructed data. Consider passing ``allow_pickle=False`` to
             load data that is known not to contain object arrays for the
             safer handling of untrusted sources.

Parameters
----------
file : file-like object, string, or pathlib.Path
    The file to read. File-like objects must support the
    ``seek()`` and ``read()`` methods. Pickled files require that the
    file-like object support the ``readline()`` method as well.
mmap_mode : {None, 'r+', 'r', 'w+', 'c'}, optional
    If not None, then memory-map the file, using the given mode (see
    `numpy.memmap` for a detailed description of the modes).  A
  

In [ ]:
a=np.load

In [129]:
np.genfromtxt?

Signature:
np.genfromtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    skip_header=0,
    skip_footer=0,
    converters=None,
    missing_values=None,
    filling_values=None,
    usecols=None,
    names=None,
    excludelist=None,
    deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~",
    replace_space='_',
    autostrip=False,
    case_sensitive=True,
    defaultfmt='f%i',
    unpack=None,
    usemask=False,
    loose=True,
    invalid_raise=True,
    max_rows=None,
    encoding='bytes',
)
Docstring:
Load data from a text file, with missing values handled as specified.

Each line past the first `skip_header` lines is split at the `delimiter`
character, and characters following the `comments` character are discarded.

Parameters
----------
fname : file, str, pathlib.Path, list of str, generator
    File, filename, list, or generator to read.  If the filename
    extension is `.gz` or `.bz2`, the file is first decompressed. Note
    that generators must r

In [130]:
from io import StringIO

In [131]:
f=StringIO(u"1,1.3,abcd")

In [135]:
data=np.genfromtxt(f,dtype=[('myint','i8'),('myfloat','f8'),('mychar','a5')],delimiter=',')

In [136]:
data

array((1, 1.3, b'abcd'),
      dtype=[('myint', '<i8'), ('myfloat', '<f8'), ('mychar', 'S5')])

In [137]:
np.eye?np

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--

In [138]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [139]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
np.eye(3,3,dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [141]:
np.eye(3,3,dtype='int32',k=-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]], dtype=int32)

In [142]:
np.eye(3,3,dtype='int32',k=1)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int32)

In [143]:
np.eye(3,3,dtype='int32',k=-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]], dtype=int32)

In [144]:
np.empty()

TypeError: empty() missing required argument 'shape' (pos 1)

In [146]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
b

array([22.  ,  4.25,  4.5 ,  4.75,  5.  ])

In [148]:
a

array([(54,  8.5, 5. +4.3j, b'sanjay'), (45, 56.5, 8. +3.5j, b'swapnil'),
       (98,  6.2, 9.3+3.j , b'chaitanya')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', '<c8'), ('f3', 'S10')])

In [149]:
np.empty_like(a)

array([( 46974096, 0.0000000e+00, 0.00000000e+00+0.0000000e+00j, b''),
       (        0, 0.0000000e+00, 5.60196527e-39+8.3819032e-07j, b'a339a9-ef0'),
       (808725817, 4.1341762e-05, 1.00154095e-11+1.7186333e-04j, b'0af74434\x94\x7f')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', '<c8'), ('f3', 'S10')])

In [150]:
a=np.linspace(4,20,9).reshape(3,3)

In [151]:
a

array([[ 4.,  6.,  8.],
       [10., 12., 14.],
       [16., 18., 20.]])

In [152]:
a.cumsum(axis=1)

array([[ 4., 10., 18.],
       [10., 22., 36.],
       [16., 34., 54.]])

In [153]:
a.cumsum(axis=0)

array([[ 4.,  6.,  8.],
       [14., 18., 22.],
       [30., 36., 42.]])

In [154]:
a.cumprod(axis=1)

array([[4.00e+00, 2.40e+01, 1.92e+02],
       [1.00e+01, 1.20e+02, 1.68e+03],
       [1.60e+01, 2.88e+02, 5.76e+03]])

In [155]:
a.diagonal()

array([ 4., 12., 20.])

In [156]:
a.repeat()

TypeError: repeat() missing required argument 'repeats' (pos 1)

In [157]:
a.repeat?

Docstring:
a.repeat(repeats, axis=None)

Repeat elements of an array.

Refer to `numpy.repeat` for full documentation.

See Also
--------
numpy.repeat : equivalent function
Type:      builtin_function_or_method


In [158]:
a.sort()

In [159]:
a

array([[ 4.,  6.,  8.],
       [10., 12., 14.],
       [16., 18., 20.]])

In [163]:
a=np.random.random((4,4))

In [164]:
a

array([[0.39090563, 0.20737405, 0.61614507, 0.24824791],
       [0.27998186, 0.73233469, 0.23315761, 0.31483316],
       [0.93608818, 0.75575135, 0.49098425, 0.77231997],
       [0.85150051, 0.60284958, 0.09659496, 0.17940232]])

In [165]:
a.sort()

In [166]:
a.sort(axis=1)

In [167]:
np.unique(a)

array([0.09659496, 0.17940232, 0.20737405, 0.23315761, 0.24824791,
       0.27998186, 0.31483316, 0.39090563, 0.49098425, 0.60284958,
       0.61614507, 0.73233469, 0.75575135, 0.77231997, 0.85150051,
       0.93608818])

In [168]:
np.full((3,3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [170]:
a=np.array([[4,5,3],[5,3,5]])

In [171]:
a

array([[4, 5, 3],
       [5, 3, 5]])

In [172]:
np.tile(a,(2,1))

array([[4, 5, 3],
       [5, 3, 5],
       [4, 5, 3],
       [5, 3, 5]])

In [173]:
np.tile(a,(1,2))

array([[4, 5, 3, 4, 5, 3],
       [5, 3, 5, 5, 3, 5]])

In [174]:
a

array([[4, 5, 3],
       [5, 3, 5]])

In [175]:
a.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'